### PR TITLE
expose chart ref

### LINKED ISSUE #6: Expose chart ref?
This element is a pure FC for the time being, sometimes we would like to access the chart instance directly. 

Say, using `chartjs-plugin-zoom`, sometimes we would do a `chartRef.resetZoom()` when a reset button is clicked.

Thx

### PR DESCRIPTION
**Pull request by ace-han**
This pull request resolves #6, taking advances of `React.forwardRef` and `React.useImperativeHandle`

## Breaking Changes

```javascript
// No more
import { ReactChart } from 'chartjs-react';
ReactChart.register(...);

// Do below
import { ReactChart, register } from 'chartjs-react';
register(...);

// It's no good to add arbitrary props or functions to an FC in TypeScript.
// Let's be definitely typed!
```

## Demo

https://codesandbox.io/s/musing-stallman-wbq7s?file=/src/App.tsx

https://codesandbox.io/s/musing-stallman-wbq7s?file=/src/ReactChartWithRegister.tsx
> It's hard to get `register` under `ReactChart` however...

### CODE REVIEW

**Comment by ace-han** [comment]
Ok. I did a little digging. It's okay to keep `ReactChart.register.

Please refer to https://codesandbox.io/s/musing-stallman-wbq7s?file=/src/ReactChartWithRegister.tsx

However, this would make code a little more complicated. What do you think?

Looking forward to your feedback. I make another pull request if necessary.

Best Regards, 

Ace

**Comment by ace-han** [comment]
Ok. I did a little digging. It's okay to keep `ReactChart.register`.

Please refer to https://codesandbox.io/s/musing-stallman-wbq7s?file=/src/ReactChartWithRegister.tsx

However, this would make the code a little more complicated. What do you think?

Looking forward to your feedback. I could make another pull request if necessary.

Best Regards, 

Ace

**Comment by xr0master** [comment]
Hey! First, I want to apologize for this delay and thank you for your participation.
1. `ReactChart.register` -  the main idea was to align the syntax with Chart.js to make the wrapper easier to use. I think that this is exactly what we have achieved, so I don’t see any reason to change the syntax yet.
2. The `forwardRef`. I once had a similar solution in my mind, but the main problem is that such a solution does little for end-users. One of the main ideas for giving users the ref to the instance is to allow them to add listeners for events like click or hover. As in request: https://github.com/xr0master/chartjs-react/issues/3
In addition, the ref will be null while the canvas element is not mounted, which requires end-users to constantly check if there is an instance.

On the other hand, though... Most of the API will be available
https://www.chartjs.org/docs/next/developers/api

**Comment by xr0master** [comment]
After some thought, I still think that such a pattern will not be stable and effective. At the moment, I added the ability to specify the chart ID, which makes it possible to get an instance through the API Chart.
``` ts
const myChartInstance = Chart.getChart('unique-chart-id');
```

Thank you very much!

**Pull request closed without merging**
